sudo: false
language: python

# this list can be easily checked by running `tox -l`
matrix:
  include: 
    

    # the dist: xenial, sudo: true settings are currently needed to test with python 3.7
    - { python: "3.7", env: TOX_ENV=py37-django20-async, dist: xenial, sudo: true }
    - { python: "3.7", env: TOX_ENV=py37-django20-sync,  dist: xenial, sudo: true }
    - { python: "3.7", env: TOX_ENV=py37-django21-async, dist: xenial, sudo: true }
    - { python: "3.7", env: TOX_ENV=py37-django21-sync, dist: xenial, sudo: true }
    - { python: "3.7", env: TOX_ENV=py37-django30-async, dist: xenial, sudo: true }
    - { python: "3.7", env: TOX_ENV=py37-django30-sync,  dist: xenial, sudo: true }
 
    # the dist: xenial, sudo: true settings are currently needed to test with python 3.8
    - { python: "3.8", env: TOX_ENV=py38-django30-async, dist: xenial, sudo: true }
    - { python: "3.8", env: TOX_ENV=py38-django30-sync,  dist: xenial, sudo: true }
    
install: pip install tox-travis coveralls

script: tox -e $TOX_ENV

after_success: coveralls
